const Data = [
    {
        id: "1",
        image: require("./Image/js.png"),
        description: "Java has been used since the beginning of the World Wide Web to improve websites and add interactive capabilities like buttons and app widgets.",
        course1: "HTML",
        course2: "SCC",
        course3: "[JAVASCRIPT,NET.JS]",
        price: 10000,
    },
    {
        id: "2",
        image: require('./Image/flask.png'),
        description: "The visual and interactive features of websites are programmed by this professional.",
        course1: "HTML",
        course2: "SCC",
        course3: "[PHP,flASK]",
        price: 17000,
    },
    {
        id: "3",
        image: require('./Image/larawel.jpeg'),
        description: "This type of software developer specializes in the design and creation of video games using coding for graphics and interactivity",
        course1: "HTML",
        course2: "SCC",
        course3: "[php,larawel]",
        price: 21000,
    },
    {
        id: "4",
        image: require('./Image/pythan4.jpeg'),
        description: "An individual in this occupation develops and tests software for personal computers. ",
        course1: "HTML",
        course2: "SCC",
        course3: "[pythan,TurboGears]",
        price: 12000,
    },
    {
        id: "5",
        image: require('./Image/java2.jpg'),
        description: "This quality assurance professional oversee the development process for software function and design. ",
        course1: "C#",
        course2: "C++",
        course3: "[JAVA,SHIFT]",
        price: 24000,
    },
    {
        id: "6",
        image: require('./Image/kotlin.jpeg'),
        description: "Education-oriented languages can help to teach computer programming and coding to novices who are unfamiliar with the processes.",
        course1: "SHIFT",
        course2: "SCC",
        course3: "[kOTLIN,ANDROID]",
        "fee": 11000,
    },
    {
        id: "7",
        image: require('./Image/react.js2.jpeg'),
        description: "This type of programmer designs and creates applications for computers or mobile devices.",
        course1: "HTML",
        course2: "SCC",
        course3: "[JAVASCRIPT,REACT.JS]",
        "fee": 18000,
    },
    {
        id: "8",
        image: require('./Image/react-native.png'),
        description: "Object-oriented language identifies everything it encounters as objects that have internal and external data and then it performs based on moving these ",
        course1: "SCC",
        course2: "REACT.JS",
        course3: "[JAVASCRIPT,REACT-NATIVE]",
        "fee": 40000,
    },
    {
        id: "9",
        image: require('./Image/nodejs.webp'),
        description: "Declarative languages tell a computer what needs to be done without including instructions for how to complete the task.",
        course1: "HTML",
        course2: "SCC",
        course3: "[JAVASCRIPT,NODE.JS]",
        price: 18000,
    },
    {
        id: "10",
        image: require('./Image/nextjs.jpeg'),
        description: "Scripting languages solve smaller programming issues and can be used to write operating system utilities.",
        course1: "HTML",
        course2: "SCC",
        course3: "[JAVASCRIPT,NEXT.JS]",
        price: 14000,
    },
    {
        id: "11",
        image: require('./Image/mangodb.png'),
        description: "Front end development languages are used to code the visual aspects of websites, games, software and apps.",
        course1: "HTML",
        course2: "SCC",
        course3: "[JAVASCRIPT,MONGO DB]",
        price: 10000,
    },
    {
        id: "12",
        image: require('./Image/php4.png'),
        description: "World Wide Web display languages are used to design web pages and provide them with the desired functions,",
        "course1": "HTML",
        course2: "SCC",
        course3: "[PHP,PHPixie]",
        price: 15000,
    },
    {
        id: "13",
        image: require('./Image/django.jpeg'),
        description: "Database programming languages help to create databases and manipulate the way data is stored inside them. Examples include C++, COBOL, Java and Perl. ",
        "course1": "HTML",
        course2: "SCC",
        course3: "[PYTHAN,Django ]",
        price: 20000,
    },
    {
        id: "14",
        image: require('./Image/project.jpeg'),
        description: "Back end coding languages code program servers so that web pages appear and function correctly. Examples include Python, Java and Ruby.",
        course1: "HTML",
        course2: "SCC",
        course3: "[PYTHAN,Pylons project]",
        price: 22000,
    },

]

export default Data;